In [1]:
###Code that, given a binary matroid finds if it has a hamilton cycle.

import numpy as np
import itertools


In [2]:
## n is the dimension as in F^n_2
## m is the size of the matroid
## k is the length of the cycle we are looking for


def cyclefinder(A, n, m, k):
    ###This code finds all the 0,1 vectors of length M
    lst = list(itertools.product(np.array([0, 1],dtype=int), repeat=m))
    ###this code finds the nullspace
    lst2=[]
    #print("Nullspace: ")
    for y in lst:
        C=np.dot(y,A)
        for x in range(len(C)):
            C[x]=C[x]%2
        a=C.sum()
        if(a==0):
            #print(y)
            lst2.append(y)
    ###This code finds the cycles of length n+1
    lst3=[]
    #print("Cycles of length ", k,":")
    for y in lst2:
        z=np.array(y,dtype=int)
        a=z.sum()
        if(a==(k)):
            lst3.append(z)
            #print(z)

    ###This code finds the smaller cycles inside the cycles of length n+1
    isHamiltonian=False
    for y in lst3:
        lst4=[]
        #print("Possible first vector:")
        #print(y)
        #print("Nullspace vectors it contains:")
        for w in lst2:
            aux=0
            for k in range(len(y)):
                if(w[k]>y[k]):
                    aux=1
            if(aux==0):
                lst4.append(w)
        #print(lst4)
        if(len(lst4)==2):
            isHamiltonian=True
    if(isHamiltonian==True):
        print("Hamiltonian: Yes")
    else:
        print("Hamiltonian: No")
            

In [3]:
## I_1 x C_3
## Rank:  3
## Cycle we are looking for: 4 
## dimension: 3
M1=[[1]]
M2=[[1,0], [0,1], [1,1]]

M3=[]
for y in M1:
    for z in M2:
        M3.append(np.concatenate((y,z)))
M4=np.array(M3)
print(M4)


[[1 1 0]
 [1 0 1]
 [1 1 1]]


In [4]:
print("I_1 x C_3")
cyclefinder(M4,3,3,4)

I_1 x C_3
Hamiltonian: No


In [5]:
## I_3 x C_3
## Rank:  5
## Cycle we are looking for: 6 


M1=[[1,0,0],[0,1,0],[0,0,1]]
M2=[[1,0], [0,1], [1,1]]

M3=[]
for y in M1:
    for z in M2:
        M3.append(np.concatenate((y,z)))
M4=np.array(M3)
#print(M4)


In [6]:
print("I_3 x C_3")
cyclefinder(M4,5,9,6)

I_3 x C_3
Hamiltonian: Yes


In [7]:
## I_5 x C_3
## Rank 
M1=[[1,0,0,0,0],[0,1,0,0,0],[0,0,1,0,0],[0,0,0,1,0],[0,0,0,0,1]]
M2=[[1,0], [0,1], [1,1]]

M3=[]
for y in M1:
    for z in M2:
        M3.append(np.concatenate((y,z)))
M4=np.array(M3)
#print(M4)


In [8]:
print("I_5 x C_3")
cyclefinder(M4,7,15,8)

I_5 x C_3
Hamiltonian: No


In [11]:
## I_7 x C_3
## Rank 
M1=[[1,0,0,0,0,0,0],[0,1,0,0,0,0,0],[0,0,1,0,0,0,0],[0,0,0,1,0,0,0],[0,0,0,0,1,0,0],[0,0,0,0,0,1,0],[0,0,0,0,0,0,1]]
M2=[[1,0], [0,1], [1,1]]

M3=[]
for y in M1:
    for z in M2:
        M3.append(np.concatenate((y,z)))
M4=np.array(M3)
print(M4)


[[1 0 0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1 1]
 [0 1 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 1 1]
 [0 0 1 0 0 0 0 1 0]
 [0 0 1 0 0 0 0 0 1]
 [0 0 1 0 0 0 0 1 1]
 [0 0 0 1 0 0 0 1 0]
 [0 0 0 1 0 0 0 0 1]
 [0 0 0 1 0 0 0 1 1]
 [0 0 0 0 1 0 0 1 0]
 [0 0 0 0 1 0 0 0 1]
 [0 0 0 0 1 0 0 1 1]
 [0 0 0 0 0 1 0 1 0]
 [0 0 0 0 0 1 0 0 1]
 [0 0 0 0 0 1 0 1 1]
 [0 0 0 0 0 0 1 1 0]
 [0 0 0 0 0 0 1 0 1]
 [0 0 0 0 0 0 1 1 1]]


In [13]:
cyclefinder(M4,9,21,10)

Hamiltonian: No


In [9]:
## I_1 x C_4'
##Rank 
M1=[[1]]
M2=[[0,0],[1,0], [0,1],[1,1]]


###This code finds the product M1 x M2
M3=[]
for y in M1:
    for z in M2:
        M3.append(np.concatenate((y,z)))
M4=np.array(M3)
print(M4)

[[1 0 0]
 [1 1 0]
 [1 0 1]
 [1 1 1]]


In [10]:
cyclefinder(M4, 3, 4, 4)

Hamiltonian: Yes


In [16]:
## I_3 x C_5

M1=[[1,0,0],[0,1,0],[0,0,1]]
M2=[[1,0,0,0],[0,1,0,0], [0,0,1,0],[1,1,1,1]]


###This code finds the product M1 x M2
M3=[]
for y in M1:
    for z in M2:
        M3.append(np.concatenate((y,z)))
M4=np.array(M3)
print(M4)

[[1 0 0 1 0 0 0]
 [1 0 0 0 1 0 0]
 [1 0 0 0 0 1 0]
 [1 0 0 1 1 1 1]
 [0 1 0 1 0 0 0]
 [0 1 0 0 1 0 0]
 [0 1 0 0 0 1 0]
 [0 1 0 1 1 1 1]
 [0 0 1 1 0 0 0]
 [0 0 1 0 1 0 0]
 [0 0 1 0 0 1 0]
 [0 0 1 1 1 1 1]]


In [17]:
cyclefinder(M4, 7, 12, 8)

Hamiltonian: No
